### ISSUE TITLE
Implement scalable event tracking following spike

### ISSUE THREAD

**Issue by j-pendlebury** [bbc/simorgh#3367]
**Is your feature request related to a problem? Please describe.**
A scalable approach to event tracking based on event listener and data attributes

**Describe the solution you'd like**
Message from https://github.com/bbc/simorgh/issues/3365
>I think this should work as a context around the application. You add a click listener to the document, and use const { addListener } = useContext(EventContext) then call addListener('click', 'navigation', frontpageNavClickHandler). This addListener function will add the click event type onto an object.
>
>When a click happens on the page, it checks the data-type attribute, if it equals ('navigation') it calls the frontpageNavClickHandler function. This function does all the ATI stuff for you.
>
>The advantage of this is its scaleable to any type of event listener and any number of them. This also has the advantage of only creating 1 event listener on the whole page, not 1 per type or 1 per item, which is better for performance
>
>(this is a rough idea, so may need cleaning up)

In the UserContext add a `addListener` function that stores data attributes to check when clicks happen on the document.
e.g.

pseudo code

**On load**

attach event listner to document

call `addListener('data-nav', functionToCall)`

This adds `'data-nav', functionToCall` to an array

**On Click**
Get event, loop over array

If element has data attribute `data-nav', call `functionToCall` with the event

**Testing notes**
ATI log should be logged for every click on a simorgh page.

Dev insight: Unit test

- [x] This feature is expected to need manual testing.

**Additional context**
See details on #3365 and #3366

**Comment by jamesbhobbs** [comment]
See details on https://github.com/bbc/simorgh/issues/3365 and https://github.com/bbc/simorgh/issues/3366

**Comment by chris-hinds** [comment]
@clareevansbbc do you know exactly what we want to track when it comes to click tracking. I.e. are we only tracking navigation item clicks or all clicks etc.

**Comment by clareevansbbc** [comment]
Yes we have the full spec written up in Jira tickets: 
WSFRONTPGS-177
WSFRONTPGS-178
WSFRONTPGS-179
WSFRONTPGS-180
WSFRONTPGS-181

Tanvee is the BA that wrote up the tickets and has most ATI knowledge - she should be able to answer any questions. Or let me know if you want to talk this through in more detail.

**Comment by mykeels** [comment]
I'd like to take up this task, if it's ready.

**Comment by mykeels** [comment]
- [ ] [WSFRONTPGS-177](https://jira.dev.bbc.co.uk/browse/WSFRONTPGS-177)
- [ ] [WSFRONTPGS-178](https://jira.dev.bbc.co.uk/browse/WSFRONTPGS-178)
- [ ] [WSFRONTPGS-179](https://jira.dev.bbc.co.uk/browse/WSFRONTPGS-179)
- [ ] [WSFRONTPGS-180](https://jira.dev.bbc.co.uk/browse/WSFRONTPGS-180)
- [ ] [WSFRONTPGS-181](https://jira.dev.bbc.co.uk/browse/WSFRONTPGS-181)

**Comment by mykeels** [comment]
Does WSFRONTPGS-177 mean that the event should only be tracked for Yoruba, Igbo and Pidgin locales?

If so, how do I test for those locales, locally?
