### ISSUE TITLE
Navigation Integration

### ISSUE THREAD

**Issue by tochwill** [bbc/simorgh#4571]
**Is your feature request related to a problem? Please describe.**
The new navigation designs contain a dropdown menu that is toggleable using a burger menu and a cross icon. The methods of achieving this are different from AMP to the canonical page.

Screenshots of the components in open/closed state can be seen here: https://github.com/bbc/psammead/issues/2557

**Describe the solution you'd like**
The Canonical navigation should use state to keep track of whether or not the dropdown should be displayed, and render the component accordingly.

The Psammead navigation package will export canonical presentational components for the menu toggle and dropdown components. When composing the Canonical navigation in Simorgh, include logic to toggle the dropdown state. The Psammead components will accept click handlers, which can be used to update the state of the navigation. This is described here: https://github.com/bbc/psammead/issues/2557

With AMP, we need to add a 'hidden' attribute, and use the AMP specific tap event. To see an example, the ConsentBanner in Simorgh contains an interaction that uses the AMP tap event.

The Psammead navigation package will export AMP presentational components for the menu toggle and dropdown components. When composing the AMP navigation in Simorgh, include logic to toggle the dropdown state. The Psammead components will accept click handlers, which can be used to update the state of the navigation. This is described here: bbc/psammead#2557

**Describe alternatives you've considered**

**Subtasks**

Subtasks:
- [x] Create lists for dropdown and scrollable in `index.js`   
- [x] Pass those lists as props  
- [x] Fix tabbing issue - fixing when `isScrollable` is set, the difference between server and client render.
- [x] Include translations for menu button announced text.
- [x] Add function to handle onOpen and onClose.  
- [x] How do we use AMP state initial JSON when simorgh converts quotes to escaped entities? This means that navigation toggling isn't working for AMP yet.
- [x] Figure out positioning of button and navigation. 
- [x] Add props validation in containers  
- [x] Fix button spacing with different line heights 
- [x] Fix Simorgh tests
- [x] Change nav bar color on menu opening 
    - [x] Canonical
    - [x] AMP
- [x] AMP state management
- [x] Also pull in the new version from psammead which has “clear:both” 
- [x] High contrast fix in firefox
- [x] E2E test: AMP state toggling
- [ ] Ensure front page E2E nav tests continue to work correctly
- [x] Integrate script link (and skip to content link) @Bopchy (in CR)
- [x] Add onClick handler to scriptLink that  sets cookies for chosen variant @Bopchy (in CR)
- [x] Last ‘rtl’ link not displaying properly
- [x] Make onClose and onOpen prop into one
- [x] Display nav bar when window size is increased with dropdown open
    - [x] Amp
    - [x] Canonical
- [x] Spread additional Navigation props - https://github.com/bbc/psammead/pull/2785#issuecomment-563192989
- [x] Call Navigation container NavigationContainer for consistency
- [x] Add comment to explain what hidden={isAmp} is doing
- [x] Look at refactoring creating the lists into a shared function for both navigations.
- [x] Refactor the container to choose the component required (Amp or Canonical) rather than use a ternary.
- [x] Move navigationSection in the config object into the `translations` object, and just call it 'section'.
- [x] Animations: https://github.com/bbc/simorgh/issues/4579 @OlgaLyubin and @AlistairGempf 
- [x] Remove aria-hidden and tabindex -1 from scrollable nav

**Testing notes**
Cypress tests will need to be updated to reflect the changes in navigation. We currently check for visible nav, with a skiplink to h1, and check that no links 404. We will now have the scrollable navigation and dropdown navigation to consider - and the dropdown links will not be visible until the burger menu has been selected.

We will need to manually test state management, and write a new E2E test to cover AMP state management and click handling works correctly.

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Blocked on https://github.com/bbc/psammead/issues/2557

**Comment by tochwill** [comment]
For refinement:
Two exports from psammead? amp and canonical? 

Shared dropdown component that is passed a toggle close/open:

```
export AmpDropdown = ({ closeAction, etc... }) => (
    <DropdownWrapper>
        <button on={closeAction}><CloseIcon /></button>
        <DropdownList>
            {children}
        </DropdownList>
    </DropdownWrapper>
); 
```

```
export CanonicalDropdown = ({ onClose }) => (
    <DropdownWrapper>
        <button onClick={onClose}><CloseIcon /></button>
        <DropdownList>
            {children}
        </DropdownList>
    </DropdownWrapper>
); 
```

**Comment by tochwill** [comment]
The same drowndown list components and scrollable navigation are going to be used for canonical and for AMP, with the only difference being the wrapper component and state management. I think it would be worth pairing on these tasks and doing a swarm review to try and avoid the back and forth across the board that we had with the nav components?
