### ISSUE TITLE
Refactor image with no caption cypress test

### ISSUE THREAD

**Issue by RayNjeri** [bbc/simorgh#4718]
**Is your feature request related to a problem? Please describe.**
Following PR #4704 we've had to tweak this test https://github.com/bbc/simorgh/blob/869cc9e2c14cc890dcc9f0d71d3e752956d4d3f5/cypress/integration/pages/articles/testsForCanonicalOnly.js#L53 to cater for when mediaPlayer is enabled on live on not but this is  brittle solution as we will keep on relying the ordinal position of the caption-lessfigure making the tests harder to maintain in the long run.

**Describe the solution you'd like**
- The test should be refactored and we should also find a better way of selecting elements than `div div div div`. 
- Tester and developer to collaborate on finding a better solution

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]
Cypress tests should be refactored 

- [ ] This feature is expected to need manual testing.

**Additional context**

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing
