### ISSUE TITLE
Richmedia Tracking Reporting PORTUGUESE instead of BRASIL 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6097]
**Describe the bug**
We're not reporting richmedia to ATI as we're passing the incorrect producer as the the statsObject.producer in the SMP settings. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.stage.bbc.com/portuguese/internacional-52137043?renderer_env=live
2. Play Rich media 
3. Inspect with ATI tag inspector
4. Note that the media level 2 is reported as "0", when it should be 33

**Expected behaviour**
We're reporting it as PORTUGUESE when it should be BRASIL see: http://bbc.github.io/echo-docs/documentation/reporting-ati/#producer
see this bug (same issue):https://github.com/bbc/simorgh/issues/5791

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**
Given that we have all services for MAPs on test, could we ensure that all richmedia tracking reporting is working as expected for the remaining services?
- [ ] Afaanoromoo -> AFAAN_OROMOO (media level 2 = 2) - https://www.bbc.com/afaanoromoo/oduu-51248626 
- [ ] Portuguese -> BRASIL

_Check once media player on the page_
- [ ] UKChina -> UK_CHINA (media level 2 = 93) - https://www.stage.bbc.com/ukchina/simp/51981020?renderer_env=live 
- [ ] Zhongwen -> CHINESE (media level 2 = 38) - https://www.stage.bbc.com/zhongwen/trad/world-52118220?renderer_env=live

**Additional context**

**Comment by LilyL0u** [comment]
Portuguese and Afaan Oromo now have the right level 2 number:

Portuguese - 
![Image 07-04-2020 at 16 35](https://user-images.githubusercontent.com/54575620/78689239-ffa7f100-78ed-11ea-91fa-47aaa156da66.jpg)

Afaan Oromo - 
![Image 07-04-2020 at 16 36](https://user-images.githubusercontent.com/54575620/78689251-06366880-78ee-11ea-9322-e2cf1e33cdfc.jpg)

Will wait to check ukchina and zhongwen
