### ISSUE TITLE
Parent Issue: Persian/Afghanistan IDX Page

### ISSUE THREAD

**Issue by hotinglok** [bbc/simorgh#6430]
**Documentation**
[Product/UX/Dev Documentation Notes and Links](https://paper.dropbox.com/doc/PersianAfghanistan-IDX-Page-ProductUXDev-documentation-notes--A0OJValCiEeo0bHgvtJyevZRAg-W9wyhnWdmCFGZTatcEY9q)

[**Release Checklist**](https://paper.dropbox.com/doc/Simorgh-Release-Checklist-IDX--A19wkE2lF2Ng3gppRnQi0GrIAg-SY46fC10iNPMF32usWBIw)

**Requirements**
Replicate the Front Page behaviour and UX - showing a slice for each group in the CPS data, and showing each of the Promo items in that block.
- There is no requirement to change the rules about displaying numbers of items in groups
- We must however allow blocks in FIX pages to render if they don’t have a Strapline
- Only 2 IDX assets to be render/routed to Simorgh:
  - https://www.bbc.com/ukrainian/ukraine_in_russian
  - https://www.bbc.com/persian/afghanistan

- Out of Scope:
  - There is no requirement to replicate the current social links component.
  - **(To be confirmed)** There is no requirement for these pages to have the Most Read component.

**Testing notes**
Given I’m on the url persian/afghanistan
when I see the page
Then I see the title of the page as a H1

Given I’m on the url persian/afghanistan
when I see the page
Then it is rendered following the same rules as the homepage
And the content is rendered from ares

Given I’m on the url persian/afghanistan
when I look at the navigation
Then is it is the same navigation as /persian

Given I’m on the url persian/afghanistan
when I look at the radio schedule
Then I see the dari radio schedule
AND is is showing the correct location

Given I’m looking at ATI
when I look for the page inspector
The page includes the Chapter where it is homed
AND identifies itself as (x07) as : index-section
AND has the same language as /persian

Given I’m looking at Chartbeat
when I look for the page
Then is should act like a Homepage

Given I’m looking at persian/afghanistan
when I share the Page on Twitter and Facebook
Then I get the correct Title and Description

### **Issues**
**Skeleton Page on Test**
- [x] _[both IDX pages]_ Create IDX Skeleton Pages for both Canonical and AMP - https://github.com/bbc/simorgh/issues/6422
- [x] _[both IDX pages]_ Make IDX pages available on Test - https://github.com/bbc/simorgh-infrastructure/issues/992

**Data Fetching**
- [x] [_both IDX pages]_ IDX - Add local route to Simorgh for IDX data - https://github.com/bbc/simorgh/issues/6432
- [x] _[both IDX pages]_ Access IDX endpoints via Mozart - https://github.com/bbc/simorgh-infrastructure/issues/991
- [x] _[both IDX pages]_ IDX - Fetch index data from ARES - https://github.com/bbc/simorgh/issues/6413

**UX**
- [x] _[persian/afghanistan]_ Use home page presentation rules on IDX page - https://github.com/bbc/simorgh/issues/6420
- [x] _[both IDX pages]_ Display H1 on IDX pages - https://github.com/bbc/simorgh/issues/6414

**Metadata**
- [x] _[persian/afghanistan]_ Add Metadata to IDX pagetype - https://github.com/bbc/simorgh/issues/6415

- ~What about linked data?~ 
- [x] Add linked data to IDX page -https://github.com/bbc/simorgh/issues/6621
- We need a further investigation into what metadata will need to different for the ukrainian IDX page (i.e. we will need some things to be in a different language).

**Analytics**
- [x] _[both IDX pages]_ Collect ATI & Chartbeat analytics from IDX pagetype - https://github.com/bbc/simorgh/issues/6416

**Radio Schedule**
- [x] _[persian/afghanistan]_ Add Dari Radio Schedule to /persian/afghanistan IDX page - https://github.com/bbc/simorgh/issues/6409

**Most Read**
- [x] _[persian/afghanistan]_ Display Most Read on /persian/afghanistan IDX page - https://github.com/bbc/simorgh/issues/6418

**A11y**
- [x]  _[persian/afghanistan]_ Accessibility swarm on persian/afghanistan IDX page - https://github.com/bbc/simorgh/issues/6408

**Radio Schedule Bugs**
- [x] Dari service https://github.com/bbc/simorgh/issues/6869

**CI**
- [x] Run a11y scripts on page - https://github.com/bbc/simorgh/issues/6647
- [x] Run lighthouse tests on page - https://github.com/bbc/simorgh-infrastructure/issues/1040

**Testing**
- [x] [both IDX pages] Integration/Cypress tests for IDX pages - https://github.com/bbc/simorgh/issues/6730
- [x] Integration: https://github.com/bbc/simorgh/pull/6802/files
- [x] Cypress: https://github.com/bbc/simorgh/pull/6798

**Live routing**
- [X] Persian/Afghanistan route on Live - https://github.com/bbc/simorgh-infrastructure/issues/1079
- [x] https://github.com/bbc/simorgh-infrastructure/issues/1079
- [x] https://github.com/bbc/mozart-smoke-test/pull/249

**Comment by DenisHdz** [comment]
Close as done https://www.bbc.com/persian/afghanistan 🎉
