### ISSUE TITLE
Parent issue: Replace Cypress tests with unit/integration

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6619]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Finish off in-progress refactors - see linked pull requests

- For each test in Cypress, we should review - can it be a unit test? If not, can it be an integration test?

- We should write brief advice - "should this be tested via unit/integration/cypress user journeys?"

- Testers should be involved in all of these discussions. 

- Sub issues grouped here: https://github.com/bbc/simorgh/milestone/89

**Describe alternatives you've considered**

**Testing notes**

**Additional context**
- https://paper.dropbox.com/doc/Simorgh-Integration-tests-for-pages--A0biD4IIc9x_4S3DXily1p~gAg-dj7GKgjKZGWNMxPOpgxyp
- Brainstorm of Automated Test issues - https://metroretro.io/board/ByppKBYqU
- https://paper.dropbox.com/doc/E2E-Tests--A0rbkkbQnGBCIh7h~faTsEweAg-hW9KxI5VIfsUPvBQbn5Yu

**Definition of Done**
- [ ] Integration tests for 41 services
- [ ] Cypress tests migrated to integration tests - header, footer, seo/metadata
- [ ] Runtime of Cypress tests under a threshold Test: 3h Live: 2h?
