### ISSUE TITLE
Parent Issue: ukraine/ukraine_in_russian IDX Page

### ISSUE THREAD

**Issue by benjifellows** [bbc/simorgh#6850]
**Documentation**
[Product/UX/Dev Documentation Notes and Links](https://paper.dropbox.com/doc/PersianAfghanistan-IDX-Page-ProductUXDev-Documentation-Table--A1hFxHSgMMNC3kaTVAkJIV0oAg-J5Liyf0gFKizW8AypqTxK)

[Release Checklist](https://paper.dropbox.com/doc/Simorgh-Release-Checklist-ukrainianukraine-in-russian--A24XW1hRmJggbVKH0vgjstmFAg-S6bsmYOBXoqnuvBABkiY6)

### **Requirements**
Replicate the Front Page behaviour and UX - showing a slice for each group in the CPS data, and showing each of the Promo items in that block.

There is no requirement to change the rules about displaying numbers of items in groups

Only 2 IDX assets to be render/routed to Simorgh:
- https://www.bbc.com/ukrainian/ukraine_in_russian
- https://www.bbc.com/persian/afghanistan

**Out of Scope:**
- There is no requirement to replicate the current social links component.
- (To be confirmed) There is no requirement for these pages to have the Most Read component.

### **Issues:**

- [X] Ensure timestamps use Ukrainian timezone -  https://github.com/bbc/simorgh/issues/6859
- [X] Pass correct language codes to components - https://github.com/bbc/simorgh/issues/6848
- [X] Add Ukraine in Russian translations - https://github.com/bbc/simorgh/issues/6846

**Metadata**
- [X] Ensure that page metadata is in the correct language - https://github.com/bbc/simorgh/issues/6854 

**UX**
- [X] UX review once the above work is on the TEST env

**A11y**
- [x] 2 dev accessibility swarm https://github.com/bbc/simorgh/issues/7084

**Testing**
- [X] Integration tests https://github.com/bbc/simorgh/issues/7027

**Live routing**
- [X] Set up live routes - https://github.com/bbc/simorgh-infrastructure/issues/1099

**Comment by greenc05** [comment]
@benjifellows what is strapline in this context please "We must however allow blocks in FIX pages to render if they don’t have a Strapline"

**Comment by benjifellows** [comment]
> @benjifellows what is strapline in this context please "We must however allow blocks in FIX pages to render if they don’t have a Strapline"

@greenc05 This has been taken from the requirements from https://github.com/bbc/simorgh/issues/6430 which came from the requirements on Confluence

**Comment by jimjohnsonrollings** [comment]
The strapline is what we render as the H2 above each group of promos.  The expectation is that if a group in the data does not have a strapline, then it should be considered a continuation of the content falling under the previous strapline/H2.

**Comment by greenc05** [comment]
@jimjohnsonrollings in that case the promos will need to be inside the previous h2's region landmark, otherwise they will not appear as a clear continuation.

**Comment by jimjohnsonrollings** [comment]
Maybe the right thing to do is to flatten them down in the preprocessor in this scenario into a single group?

**Comment by greenc05** [comment]
Sounds good @jimjohnsonrollings

**Comment by jimjohnsonrollings** [comment]
Worth noting that this issue relates to an IDX, not an FIX, so that requirement doesn't apply here

**Comment by greenc05** [comment]
It's been added to the FIX issue https://github.com/bbc/simorgh/issues/6832 @jimjohnsonrollings

**Comment by DenisHdz** [comment]
Close as done https://www.bbc.com/ukrainian/ukraine_in_russian  🎉
