### ISSUE TITLE
Includes - incremental front-end refactor

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#6883]
## Is your feature request related to a problem? Please describe.

All rendering logic for Includes currently exists within the Includes container. As we begin to support different types of Includes we should refocus this container's responsibility, with the goal of improving how readable and maintainable this area of our codebase is.

### Strategy Pattern
> The strategy pattern...is a behavioural software design pattern that enables selecting an algorithm at runtime. – Wikipedia

Where an algorithm is one of six Include components – each having little in common:

```js
const components = {
  amp: {
    idt1: props => <Idt1IncludeAmp {...props} />,
    idt2: props => <Idt2IncludeAmp {...props} />,
    vj: props => <VjIncludeAmp {...props} />,
  },
  canonical: {
    idt1: props => <Idt1IncludeCanonical {...props} />,
    idt2: props => <Idt2IncludeCanonical {...props} />,
    vj: props => <VjIncludeCanonical {...props} />,
  },
};
```

And the Include container's responsibility to select one at runtime, and pass it data:

```js
const IncludeContainer = props => {
  const { isAmp } = useContext(RequestContext);
  const { type } = props;

  const platform = isAmp ? 'amp' : 'canonical';

  return components[platform][type]
    ? components[platform][type](props)
    : null;
};
```

## Note
Initial steps to kick off this work will be introduced in the following PR https://github.com/bbc/simorgh/pull/6672. The purpose of _this_ issue is to guide in-flight (like the aforementioned) and future issues to make the necessary changes we need to complete this refactor in an incremental way.

### 1. Migrate Canonical components
We should migrate Canonical components to three individual files and move shared logic into `common.jsx` within the components directory.
```
Include/
  components/
    common.jsx
    Canonical/
      Idt1CanonicalInclude.jsx
      Idt2CanonicalInclude.jsx
      VjCanonicalInclude.jsx
```

#### Issues that could contribute to this
- [x] Use fallback image for IDT2 Maps and Charts on Canonical #6837

---

### 2. Migrate AMP components
We should migrate AMP components to three individual files and move shared logic into `common.jsx` within the components directory.
```
Include/
  components/
    common.jsx
    Amp/
      Idt1AmpInclude.jsx
      Idt2AmpInclude.jsx
      VjAmpInclude.jsx
```

#### Issues that could contribute to this
- [x] Render VJ Include on AMP in fixed size iframe #6917
- [x] Add AMP Support for IDT2 Includes #6563
- [x] If VJ Include has an AMP alternative, ensure we fetch it and make it available #5989
- [x] Show include placeholder when no AMP version available #5987

---

### 3. Update Includes container
We should ensure the Includes container is functioning as expected and make any updates if necessary.
```
Include/
  index.jsx
```

## Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

## Additional context
None.
