### ISSUE TITLE
[Parent Issue] Ukrainian STYs

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#7228]
## Background

There are multiple languages commonly used in Ukraine, including Ukrainian and Russian. BBC Ukrainian has chosen to produce and publish content in both [Ukrainian](https://www.bbc.com/ukrainian) and [Russian](https://www.bbc.com/ukrainian/ukraine_in_russian).

The WS Engage team will be responsible for ensuring STYs published by BBC Ukrainian support both Russian and Ukrainian languages.

## BBC Ukrainian

Here is:

1. An STY on BBC Ukrainian written in Ukrainian:
https://www.test.bbc.com/ukrainian/features-53407150?renderer_env=live

2. An STY on BBC Ukrainian written in Russian:
https://www.test.bbc.com/ukrainian/news-russian-53373654?renderer_env=live 

In order to correctly support STYs written in Russian on BBC Ukrainian, we must complete the following issues.

#### Accessibility
- [x] Ukrainian STYs – full a11y swarm #7442
  - [x] Resolve incorrect secondary column translations and timestamps when a language override is present #7477

#### Language codes
- [x] Set service language override more inclusively #7258
- [x] Assign 'lang="uk"' to relevant Ukrainian STY page components when a language override is present #7264

#### Metadata
- [x] Ensure the HTML 'lang' attribute is updated when a language override is present #7262
- [x] Ensure that STY page metadata is updated when a language override is present #7263

#### Russian content
- [x] Ensure Related Content's heading is using the correct translation when a language override is present #7261
- [x] Ensure that timestamps use the correct configuration when a language override is present #7268
- [x] Ensure Social Embeds use the correct translations when a language override is present #7287
- [x] Ensure Media Player uses the correct translations when a language override is present #7288

### Test
- URL of test asset published to the Ukraine in Russian section of the Ukrainian service: https://www.test.bbc.com/ukrainian/news-russian-23333960

### Non-Issues
These have been considered, but cannot be worked on yet.
- Ensure 404 error messages use Russian translation
  - We have the translations, but error pages don't support translations yet(?).
- Include fallback error translations
  - We don't have the translations for these yet.

## Notes
- A `ukrainian-STYs` label is available for related issues.
- JIRA ticket: NEWSART-953.
- Story Map: https://miro.com/app/board/o9J_kvQbdPo=/?moveToWidget=3074457348877076592&cot=13.

**Comment by simonsinclair** [comment]
All issues have been completed.
