### ISSUE TITLE
Display Android App Install Banners on 4 services

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#7254]
**Is your feature request related to a problem? Please describe.**
In order to promote our Apps, we'd like to display prompts on Android devices to Install them

**Describe the solution you'd like**
The affected services are:
* Arabic
* Hindi
* Mundo
* Russian

- For these services we need to add to the manifest files code resembling:
```
"prefer_related_applications": true,
"related_applications": [
  {
    "platform": "play",
    "id": "**********"
  }
]
```

The ID values are as follows:
Service | ID 
--- | ---
Arabic | uk.co.bbc.arabic 
Hindi | uk.co.bbc.hindi 
Mundo | uk.co.bbc.mundo 
Russian | uk.co.bbc.russian 

Additionally, we need to add `*.googleusercontent.com` to the `image-src` of our Content Security Policy so that the app icon can be displayed (the docs at https://developers.google.com/web/fundamentals/app-install-banners/native do say `In some cases *.googleusercontent.com maybe more verbose than desired. It's possible to narrow this down by remote debugging an Android device to determine the URL of the app icon.`)

We have discovered that the images for the app store are:
- Arabic https://lh3.googleusercontent.com/DMLOtArx9rm35YLzA0J9SWCJmTedWCezwTeZQK3_L0lxGWwdQovvX2bbjNWA_p09ZC4
- Hindi https://lh3.googleusercontent.com/miz4L-OhDG1atvBOqxx83WxdNzdb2fWRz65rxST-enBzC52HJNTB3uzbTfwEZoO_UQ
- Mundo https://lh3.googleusercontent.com/MaLsvtOl4Ao9o9TIUmblabzDOsVwBO90emKf0JTGR3hFgRcFh6npkDRC9bwxb15MVqc
- Russian https://lh3.googleusercontent.com/qWnPnHDJ4rt0jZf32B3C1_EhObyVKc8bMtk93grZiHXasaekVSPNMzp0mhlVGKyDRTo

Therefore, we just need to add `https://lh3.googleusercontent.com` to the CSP 

### TODO
 - [x] https://github.com/bbc/simorgh/blob/latest/public/mundo/manifest.json - hardcode the ID values above, in the corresponding manifest file
- [x] Update CSP Headers to include `https://lh3.googleusercontent.com` in `img-src` https://github.com/bbc/simorgh/blob/latest/src/server/utilities/cspHeader/index.js#L436
- [x] Add tests / update snapshots where applicable

It is slightly unclear under exactly which conditions the prompt, called a `mini info-bar` in Android, will display (spec: https://developers.google.com/web/fundamentals/app-install-banners/native), but it looks like you need to be:
* Using the latest stable Chrome
* Interacting with our site for at least 30 seconds
* Not already have the app installed
* Not have dismissed the prompt within the last 3 months

**Acceptance Criteria**
Given I am using an Android device
And I am on a page on one of the above services
And I do not have the relevant Android App installed
And I am using the latest stable Chrome
And I have been interacting with the site for more than 30 seconds
Then I should see a mini-info bar prompting me to install the app

Given I am using an Android device
And I am on a page on one of the above services
And I do have the relevant Android App installed
Then I should never see a mini-info bar prompting me to install the app

Given I can see the Mini Info Bar
When I select install
Then the play store opens
And I can see the relevant Play store page

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by simonsinclair** [comment]
Re-opening for https://github.com/bbc/simorgh/pull/7948.
