### ISSUE TITLE
Create POC for Feature Index page

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#7714]
**Is your feature request related to a problem? Please describe.**
Support Feature Index (FIX) Pages in Simorgh

- [Simorgh Milestone](https://github.com/bbc/simorgh/milestone/116) 
- [Simorgh Infrastructure Milestone](https://github.com/bbc/simorgh-infrastructure/milestone/28)

### Routing
  - [x] Simorgh - https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/index.jsx#L28
  - [x] Route Feature Index pages on Test environment via Mozart https://github.com/bbc/simorgh-infrastructure/issues/1196

### Page Container
- [ ] 🚧 Create FeatureIndexPage from IdxPage #7824 

### Key differences between PAL & Simorgh
Identify differences between PAL rendered page and Simorgh rendered page
- [x] Out of Scope for Phase 1: Ads | Most Read | Social Media
- [x] Features and Analysis needs to be rendered as any other group and not in a secondary column
- [x] Blocks must render correctly without strapline
- [x] Amp should work

### Page Title
- [x] Implement title for Feature Index page (JIRA-1059)
Consider headline or strapline component in psammead. Reuse title from IdxPage

### Top Stories
- [x] Should render without strapline
Refer to JIRA-1062 for CPS groups used for top stories

### Sections (JIRA-1063)
- [x]  Feature Index Page Sections #7842 

### Promos (JIRA-1064)
- [x] Existing promos work as expected

### Page Metadata (JIRA-1066)
- [ ] Ati, Set x7 (page type) to `index-section`
- [ ] Chartbeat, ensure g0 parameter ends with FIX
- [ ] OG and Twitter same as IDX

### Testing
- [x] Ensure Feature Index page data in Simorgh repo for testing https://github.com/bbc/simorgh-infrastructure/issues/1197
- [x] Cypress config to allow for E2E testing, including at least 1 service for smoke testing https://github.com/bbc/simorgh/issues/7827
- [ ]  🚧 Add integration test(s) https://github.com/bbc/simorgh/issues/7830
- [ ]  🚧 Add AMP Validation, a11y & Lighthouse tests

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
