### ISSUE TITLE
[Parent Issue] Migrate from Styled Components to Emotion

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#7772]
## Outline
Following preliminary work (covered in Background 👇), we wish to migrate our CSS-in-JS library from Styled Components to Emotion. This will release us from the Styled Components shaped hole we've been stuck in since we learned we couldn't upgrade to the latest version.

In migrating to Emotion, we will leave behind Styled Components four, the stale issues with companion libraries preventing us from upgrading to Styled Components five, and likely see an exceptional increase in real-world server-side rendering time. Emotion's runtime is also smaller than Styled Components, so we will see a reduction in client-side bundle sizes.

### Psammead
- [x] Update README to notify users of move to Emotion https://github.com/bbc/psammead/issues/3765
- [x] [1/3] Install Emotion whilst being backwards compatible https://github.com/bbc/psammead/pull/3867
- [x] [2/3] Refactor "dynamic styles" and `attrs()` use for Emotion https://github.com/bbc/psammead/issues/3763
- [x] [3/3] To Emotion and beyond https://github.com/bbc/psammead/pull/3926

### Simorgh
- [x] Emotion SSR - All #8171

---

## Background
This work stemmed from the following root issue: Simorgh performance profiling #6922.
### Investigation
The following document is a living investigation, which has informed the direction of this work: [Dropbox Paper: Simorgh SSR Performance](https://paper.dropbox.com/doc/Simorgh-SSR-performance--A7TkHsPS9umCiPdfP6x~wqhVAg-z1ffIgMu97RMinpYS4blG)

#### Phase 1
- [1/2] Emotion PoC – SSR Perf. https://github.com/bbc/psammead/issues/3677
- https://github.com/simonsinclair/psammead
- https://github.com/simonsinclair/psammead-packages

#### Phase 2
- [2/2] Emotion PoC – SSR Perf. #7536
- https://github.com/simonsinclair/simorgh

#### Results

A single (non-clustered) Simorgh instance renders pages 35% faster with Emotion.

<img width="690" alt="Screenshot 2020-09-14 at 17 32 12" src="https://user-images.githubusercontent.com/1430787/93116292-fd279f80-f6b4-11ea-929b-bfc187825e94.png">
