### ISSUE TITLE
Flatten FIX Page Sections

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#7842]
**Is your feature request related to a problem? Please describe.**
Add support for different section types
Refer to JIRA-1063 for further information

**Describe the solution you'd like**
If the strapline is missing, then flatten this section and add to end of the previous section
e.g. If the strapline is missing and the previous section is top stories, then flatten this section and add to top stories

#### Feature Index Page with no sections
https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5ee8cfb1ddde9f468b2998a0

#### Limit Max Number of Promos per section
See https://www.test.bbc.com/urdu/science-51314202?renderer_env=live
e.g. Top Stories = 13, Everything else = 10
For FIX Pages, the limits should be removed

#### TODO
- [ ] Determine how YouTube / external promo links should be rendered within a section e.g. https://www.test.bbc.com/urdu/science-51314202?renderer_env=live 
- [ ] Remove limits on max number of items to display on FIX pages only. Each section will only display 2 rows of 4 with images, and 1 row of 4 without images therefore the max can only be 12-14
- [ ] Refactor renderWithoutStrapline logic added in original PR https://github.com/bbc/simorgh/blob/706edd65525153496b768b2f0d47e197f0de4fc9/src/app/containers/IndexPageSection/index.jsx#L204
- [ ] Add more test scenarios for `flattenGroups` logic
- [ ] FIX page with no straplines is only displaying 13 Top Stories, and no additional sections - lots of content missing
- [ ] If a Top Stories section does not have 1, 5, 9 or 13, then some stories will be omitted

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by paruchurisilpa** [comment]
Checked using the list here:

https://paper.dropbox.com/doc/FIX-Asset-URLs--A9HRJSq1LZuRPez3ha~lW5M1Ag-ckGczfeg6p40giKjnLFn2

LGTM..
