### ISSUE TITLE
Jenkins -> AWS CodePipeline Migration

### ISSUE THREAD

**Issue by karinathomasbbc** [bbc/simorgh#8303]
**Is your feature request related to a problem? Please describe.**
A list of tasks which need to be completed in order to successfully migrate from Jenkins -> CodePipeline

**Describe the solution you'd like**
- Use GitHub actions to replace individual tests which are run as part of the Jenkins CI pipeline
 - [x] GitHub Action: Run puppeteer tests as part of PR checks #8302 
- [x] Add GH Actions for unit and integration tests #8196 
- [x]  Remove travis config and travis build badge #8245 
- [x]  Chromatic actions #8268 
- [x]  Github Actions: Lighthouse tests & npm audit #8270 
- [x]  GitHub action to create a tag and release when pushing to latest #8277 
- [x]  Remove unused buildspec and add cc test reporting from GH actions #8301 
-  [x] Use merge commit as release notes for release created by GitHub actions #8298 
- Remove Jenkinsfile from Simorgh
- Delete `test:ci` command from `package.json` as it is no longer required
- Delete some & move others 3rdPartyCypress tests
-  Refactoring 3rd party cypress tests #8300 
- ... and many more

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
