### ISSUE TITLE
Implement CSR for media promos

### ISSUE THREAD

**Issue by RichardPK** [bbc/simorgh#8535]
**Release blocked by**
- [ ] Reduce amount of HoCs under renderRoutes #8554 
- [ ] Improve client side routing UX for assistive tech #8531 
- [ ] Implement UX skeleton for CSR loading transitions #8533 

**Is your feature request related to a problem? Please describe.**
- One of the components initially targeted for implementing CSR for is media promos (appearing on front page/recent eps/most watched)
- We should use React Router Link components rather than anchor tags to enable these links.

**Describe the solution you'd like**
- Some of the work required within Simorgh to implement this has also already been explored as part of the media CSR week, [code here](https://github.com/bbc/simorgh/pull/8510/files#diff-a6a0cb954b20b946fc6a9c2a39c927ddffe777fdb152b657f27c15113e57896dR212)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
