### ISSUE TITLE
[Parent] Update AMP and Canonical Consent Banners

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#8668]
### Is your feature request related to a problem? Please describe.

We need to update the AMP Consent Banner design, functionality and content. The Canonical Consent Banner is being updated in Psammead and this issue will integrate those changes.

#### In-flight
- [x] https://github.com/bbc/simorgh/issues/8696 – Canonical, move Consent Banner
- [x] https://github.com/bbc/psammead/issues/4216 – Canonical, update component design
- [x] https://github.com/bbc/psammead/issues/4290 – Canonical, UX & A11y amendments
- [x] https://github.com/bbc/simorgh/issues/8751 – AMP, Translations
- [x] https://github.com/bbc/simorgh/issues/8810 – Update E2E coverage

#### Parent PR
- [ ] https://github.com/bbc/simorgh/pull/8718 – Base Branch

The updated AMP Consent Banner design can be found at the following location: https://zpl.io/bzKPwKA. It shows that on top of updating the design, we need to add functionality in the form of 'paging' content when a user clicks "Manage my settings". This can be achieved with `amp-bind`, as explored in the following spike: https://github.com/bbc/psammead/pull/4174.

Page 1 – https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5f9ff5ccbf4e222d67e1432d
Page 2 – https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5f9ff565a46abd4569174e7a

### Describe alternatives you've considered
N/A.

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
![ambannerflow](https://user-images.githubusercontent.com/1430787/104318508-6c809500-54d7-11eb-8232-efd75ccef5dc.png)
