### ISSUE TITLE
[Parent] Update AMP Consent Banner

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#8669]
### Is your feature request related to a problem? Please describe.

We are in the process of updating the Consent Banner. This parent issue collates the AMP specific issues and should be closed when they are complete. Please see below.

### Describe the solution you'd like

- [ ] Implement pageable Consent Banner content https://github.com/bbc/psammead/issues/4215
- [ ] Configure AMP Consent Banner's secondary content #8668

### Describe alternatives you've considered
N/A.

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context

![composition](https://user-images.githubusercontent.com/1430787/104315808-6d172c80-54d3-11eb-829f-b8c2e4693fc1.png)

**Comment by simonsinclair** [comment]
This work has been restructured and no longer needs a parent issue.
